# ===============================

# MYSQL CONFIG

# ===============================

spring.datasource.url=${MYSQL_URL:jdbc:mysql://localhost:3306/queueease_db}
spring.datasource.username=${MYSQL_USERNAME:root}
spring.datasource.password=${MYSQL_PASSWORD:Manshi@263}

# ===============================

# JPA / HIBERNATE

# ===============================

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect

# ===============================

# SERVER

# ===============================

server.port=${PORT:8080}
server.address=0.0.0.0

# ===============================

# ERROR LOGGING

# ===============================

server.error.include-message=always
server.error.include-binding-errors=always

logging.level.org.springframework=DEBUG

# ===============================

# MONGODB ATLAS

# ===============================

spring.data.mongodb.uri=mongodb+srv://queueease:queueease123@cluster0.3eelujn.mongodb.net/queueease?retryWrites=true&w=majority&appName=Cluster0
