spring.datasource.url=jdbc:mysql://localhost:3306/queueease_db
spring.datasource.username=root
spring.datasource.password=Manshi@263

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
server.error.include-message=always
server.error.include-binding-errors=always
logging.level.org.springframework=DEBUG

spring.data.mongodb.uri=mongodb://localhost:27017/queueease_logs
server.address=0.0.0.0