spring.application.name=queueease
spring.datasource.url=jdbc:mysql://localhost:3306/queueease
spring.datasource.username=root
spring.datasource.password=Manshi@263

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

spring.data.mongodb.uri=mongodb://localhost:27017/queueease